// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkovlxsvbspcuufrpvhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indrb3ZseHN2YnNwY3V1ZnJwdmhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NDM5NzYsImV4cCI6MjA2NjUxOTk3Nn0.MMZc-Ny1EIBkRMyicOOycKn2PCoefFh7vYHGPWD8SMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);